### ISSUE TITLE
request SDE dataset explanation

### ISSUE THREAD

**Issue by HyunsuYEE** [EthanLiang99/EvLight#1]
hello.
I'm interested in using your SDE dataset.
I want to know what is the meaning of tuple in event stream.
when I decompress the .npz file in low light dataset(SDE), it is the numpy, which has shape [(186, 346, 260)].
But, I want to know why the tensor's element is tuple? (not binary number which is corresponding polarity via threshold)

can you explain what is the meaning of 6-sized tuples?
<img width="385" alt="image" src="https://github.com/EthanLiang99/EvLight/assets/113850887/da08fac2-f6f9-4c6d-ac97-67c075b12dc2">

should I align the event dataset's polarity with timestamp & x & y?
I want to know how to process this 6-tuple event dataset.

**Comment by EthanLiang99** [comment]
It seems like you are loading the lowligt_event.npz (the whole low-light event stream), which is same as the orginal format of DAVIS event camera. If yes, pls try:
```
if self.events.ndim == 1:
   et = self.events["timestamp"]
   ex = self.events["x"]
   ey = self.events["y"]
   ep = self.events["polarity"]
```
If you are using the xxx.npz (split low-light event streams), pls try:
```
et = event[0, 0]
ex = event[:, 1]
ey = event[:, 2]
ep = event[:, 3]
```
