### ISSUE TITLE
执行sh文件之后，没有训练

### ISSUE THREAD

**Issue by DopeRita** [EthanLiang99/EvLight#10]
您好，根据您的提示，已经进行了如下操作：
 options/test/xxx.yaml 中更改模型和数据集的路径。
options/train/xxx.yaml 中更改数据集的路径。
但是执行sh options/test/xxx.sh和sh options/train/xxx.sh语句之后，输出如图，没有开始模型的训练，请问是什么原因？
十分感谢您的解答！
<img width="496" alt="1110-问题1" src="https://github.com/user-attachments/assets/b687fbd9-74ca-4bb4-afe5-85512d6dafea">
<img width="1262" alt="1110-问题2" src="https://github.com/user-attachments/assets/ab134414-6d90-4877-b379-b71407b08dfc">
<img width="1259" alt="1110-问题3" src="https://github.com/user-attachments/assets/ce9edf12-24b3-4188-810f-6ce30d3e52d1">

**Comment by DopeRita** [comment]
在git bash中运行sh文件结果如图
<img width="1280" alt="1110-问题4" src="https://github.com/user-attachments/assets/e97d96ba-018e-414c-b7c4-c96aa69dbecd">

**Comment by EthanLiang99** [comment]
从截图上看你是执行了set_trace()的命令进入了pudb的窗口，理论上正常的训练和测试不会进入。可以尝试检查.sh文件是否修改，或者最直接的方法是删除代码中所有set_trace()

**Comment by DopeRita** [comment]
非常感谢，按照您说的第二种方法，这个问题解决了。

**Comment by DopeRita** [comment]
> 从截图上看你是执行了set_trace()的命令进入了pudb的窗口，理论上正常的训练和测试不会进入。可以尝试检查.sh文件是否修改，或者最直接的方法是删除代码中所有set_trace()

非常感谢，按照您说的第二种方法，这个问题解决了。

**Comment by EthanLiang99** [comment]
好的，我之后检查一下代码处理一下这个问题
