### ISSUE TITLE
 Request for Normal Light Event Data in SDE Dataset

### ISSUE THREAD

**Issue by XXN-1N** [EthanLiang99/EvLight#11]
Hello!

First of all, thank you for your work on the SDE dataset. It has been incredibly useful for my research.

I noticed that the SDE dataset currently only includes event data captured under low light conditions. I was wondering if it would be possible to supplement this with event data captured under normal lighting conditions.

**Comment by EthanLiang99** [comment]
Thanks for your interest!

We have uploaded normal-light events here: [onedrive](https://hkustgz-my.sharepoint.com/:f:/g/personal/gliang041_connect_hkust-gz_edu_cn/EtFRcH270mlNmXjgECTgrAgBsUA-qIRTuSzRtoNuGLa38g). 

Please feel free to check it out. I want to highlight that all of the alignment processes are designed to ensure consistency between normal-light and low-light images and **the consistency of these events in different illumination has not yet been evaluated.**
