### ISSUE TITLE
Details about the experiment

### ISSUE THREAD

**Issue by Shecyy** [EthanLiang99/EvLight#4]
Hello, thank you so much for sharing these two datasets.
According to your paper, I found that the ablation experiment was performed on the SDE-in dataset. I would like to ask how you obtained the experimental results in Table 2. Do you train on the SDE-in training datasetset and SDE-out training datasetset separately, and then inference separately? Or do you train directly on all the training datasetsets of SDE and then inference separately?

The same problem described above exists with respect to the SDSD dataset.

![image](https://github.com/user-attachments/assets/81dd485f-824f-4bf1-8069-9ecf5b5ac4f4)

**Comment by EthanLiang99** [comment]
We trained and inferecned on the corresponsidng datasets respetively, which is similar to the previous work SNR-Aware Low-light Image Enhancement and Retinexformer: One-stage Retinex-based Transformer for Low-light Image Enhancement.

**Comment by Shecyy** [comment]
Thank you for your clarification.
