### ISSUE TITLE
Event Data

### ISSUE THREAD

**Issue by DachunKai** [EthanLiang99/EvLight#6]
I noticed that an ND8 filter was used when capturing low-light RGB images. May I ask if the same ND filter was used in front of the camera when collecting event data?

**Comment by DachunKai** [comment]
Sorry, I have a misunderstanding. Since the RGB and event sensors of the DAVIS camera are synchronized, the ND8 filter placed in front of the camera affects both sensors simultaneously. Therefore, the ND filter is also effective for the event sensor during data collection.

**Comment by DachunKai** [comment]
Is my understanding correct that the event data in the dataset was captured with an ND filter?

**Comment by EthanLiang99** [comment]
yes....Maybe you can check the [website ](https://inivation.com/buy/#)to help you know more about event cameras.

**Comment by DachunKai** [comment]
Thanks,I'm familiar with event camera😀.
